version: '3'

services:
  postgres:
    image: postgres_django  # Use a imagem criada anteriormente (substitua se necessário)
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
